# 1.create  a 3x3x3 array with random values


In [17]:
import numpy as np

# Create a 3x3x3 array with random values between 0 and 1
random_array = np.random.rand(3, 3, 3)

print(random_array)


[[[0.61600105 0.67204232 0.99022882]
  [0.60068253 0.70159813 0.55779981]
  [0.47377508 0.70845216 0.90432152]]

 [[0.46928965 0.45078981 0.19183183]
  [0.27883361 0.10674639 0.04154554]
  [0.1116291  0.3257641  0.22909182]]

 [[0.17860375 0.10509624 0.86647238]
  [0.19897231 0.58905612 0.81665557]
  [0.50574091 0.86659737 0.38192557]]]


# 2.create  a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
import numpy as np

# Create a 5x5 matrix filled with zeros
matrix = np.zeros((5, 5))

# Fill values 1, 2, 3, and 4 just below the diagonal
for i in range(1, 5):
    matrix[i, i - 1] = i

print(matrix)


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 3.create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
import numpy as np

# Create an 8x8 matrix filled with zeros
matrix = np.zeros((8, 8), dtype=int)

# Fill the checkerboard pattern
matrix[1::2, ::2] = 1  # Rows 1, 3, 5, 7; Columns 0, 2, 4, 6
matrix[::2, 1::2] = 1  # Rows 0, 2, 4, 6; Columns 1, 3, 5, 7

print(matrix)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4.Normalize a 5x5 random matrix


In [4]:
import numpy as np

# Create a 5x5 random matrix
random_matrix = np.random.rand(5, 5)

# Calculate the mean and standard deviation of the matrix
mean_value = np.mean(random_matrix)
std_deviation = np.std(random_matrix)

# Normalize the matrix
normalized_matrix = (random_matrix - mean_value) / std_deviation

print("Original Matrix:")
print(random_matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)


Original Matrix:
[[0.56538523 0.12659522 0.51032888 0.28570363 0.21384638]
 [0.8197832  0.17073694 0.46310731 0.65368324 0.13821847]
 [0.96430357 0.5654162  0.80582567 0.53526497 0.8985754 ]
 [0.96057884 0.09498862 0.36096093 0.94405383 0.18018478]
 [0.14596547 0.89101106 0.65723438 0.54266086 0.6554347 ]]

Normalized Matrix:
[[ 0.13531317 -1.37197494 -0.05381096 -0.82542146 -1.07225839]
 [ 1.00919598 -1.22034369 -0.21602185  0.43862578 -1.33204791]
 [ 1.50563807  0.13541956  0.96125043  0.03184702  1.27985515]
 [ 1.49284324 -1.48054682 -0.566905    1.43607815 -1.18788939]
 [-1.30543617  1.25387087  0.45082431  0.05725266  0.44464222]]


# 5.how to find common values between two arrays?

In [5]:
array1 = [1, 2, 3, 4, 5]
array2 = [3, 4, 5, 6, 7]

set1 = set(array1)
set2 = set(array2)

common_values = set1.intersection(set2)
print(list(common_values))


[3, 4, 5]


# 6.how to get the dates of yesterday,today and tomorrow?

In [6]:
from datetime import datetime, timedelta

# Get today's date
today = datetime.today().date()

# Calculate yesterday's date
yesterday = today - timedelta(days=1)

# Calculate tomorrow's date
tomorrow = today + timedelta(days=1)

# Print the dates
print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2023-09-20
Today: 2023-09-21
Tomorrow: 2023-09-22


# 7.Consider two random array a  and b ,check if they are equal

In [7]:
import numpy as np

# Assuming you have two NumPy arrays a and b
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])

are_equal = np.array_equal(a, b)

if are_equal:
    print("Arrays are equal.")
else:
    print("Arrays are not equal.")


Arrays are equal.


# 8.create vector of size 10 and replace the maximum value by 0

In [9]:
import numpy as np

# Create a random vector of size 10
vector = np.random.rand(10)

# Find the index of the maximum value in the vector
max_index = np.argmax(vector)

# Replace the maximum value with 0
vector[max_index] = 0

print("Original Vector:")
print(vector)


Original Vector:
[0.         0.24905113 0.72666676 0.38661856 0.35597016 0.83528714
 0.69760429 0.87391663 0.16061294 0.09725749]


# 9.how to print all the values of an array ?

In [8]:
import numpy as np

my_array = np.array([1, 2, 3, 4, 5])

# Using a loop
for value in my_array:
    print(value)

# Using numpy.nditer
for value in np.nditer(my_array):
    print(value)


1
2
3
4
5
1
2
3
4
5


# 10.subract the mean of each row of a matrix?


In [10]:
import numpy as np

# Create a sample matrix (replace this with your actual matrix)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Calculate the mean of each row along axis 1 (rows)
row_means = np.mean(matrix, axis=1, keepdims=True)

# Subtract the row means from each row
normalized_matrix = matrix - row_means

print("Original Matrix:")
print(matrix)
print("\nMatrix with Row Means Subtracted:")
print(normalized_matrix)


Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix with Row Means Subtracted:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


# 11.consider a given vector,how to add 1 to  each element indexed by a second vector (be careful with repeated indices)

In [12]:
import numpy as np

# Given vector
given_vector = np.array([1, 2, 3, 4, 5])

# Second vector containing indices
indices_to_add = np.array([1, 3, 1, 4, 0])

# Create a mask to handle repeated indices
mask = np.zeros_like(given_vector, dtype=bool)

# Use np.add.at to add 1 to elements at the specified indices
np.add.at(given_vector, indices_to_add, 1)

print("Original Vector:")
print(given_vector)


Original Vector:
[2 4 3 5 6]


#  12.how to get the diagonal of a dot product?

In [11]:
import numpy as np

# Create two matrices (replace these with your matrices)
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])

# Calculate the dot product of the two matrices
dot_product = np.dot(matrix1, matrix2)

# Get the diagonal of the dot product
diagonal = np.diag(dot_product)

print("Dot Product:")
print(dot_product)
print("\nDiagonal of Dot Product:")
print(diagonal)


Dot Product:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Diagonal of Dot Product:
[30 69 90]


# 13.how to find the most frequent value in an array?

In [ ]:
import numpy as np

my_array = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5])

# Use np.unique to get unique values and their counts
unique_values, counts = np.unique(my_array, return_counts=True)

# Find the index of the maximum count
max_count_index = np.argmax(counts)

most_frequent_value = unique_values[max_count_index]
frequency = counts[max_count_index]

print("Most frequent value:", most_frequent_value)
print("Frequency:", frequency)


# 14.how to get  the n largest values of an array

In [13]:
import numpy as np

# Create a NumPy array (replace this with your array)
my_array = np.array([10, 5, 8, 20, 2, 18])

# Specify the value of n (e.g., n = 3 for the 3 largest values)
n = 3

# Use numpy.partition to find the n largest values
largest_n_values = np.partition(my_array, -n)[-n:]

print("N Largest Values:", largest_n_values)


N Largest Values: [10 20 18]


# 15.how to create  a record array from a regular array?

In [14]:
import numpy as np

# Create a regular array (a list of tuples in this example)
regular_array = [(1, 'Alice', 25),
                 (2, 'Bob', 30),
                 (3, 'Charlie', 35)]

# Define the data type and field names for the record array
dtype = [('ID', int), ('Name', 'U10'), ('Age', int)]

# Create the record array using np.array() with the specified data type
record_array = np.array(regular_array, dtype=dtype)

# Access elements by field name
print("Record Array:")
print(record_array)

# Access individual fields
print("\nAccessing individual fields:")
print("First record ID:", record_array['ID'][0])
print("Second record Name:", record_array['Name'][1])
print("Third record Age:", record_array['Age'][2])


Record Array:
[(1, 'Alice', 25) (2, 'Bob', 30) (3, 'Charlie', 35)]

Accessing individual fields:
First record ID: 1
Second record Name: Bob
Third record Age: 35


# 16.how to swap two rows of an array ?

In [15]:
import numpy as np

# Create a sample 2D array (replace this with your array)
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Specify the indices of the rows you want to swap
row_index1 = 0  # Index of the first row to swap
row_index2 = 2  # Index of the second row to swap

# Swap the rows using slicing and assignment
array[row_index1], array[row_index2] = array[row_index2].copy(), array[row_index1].copy()

# Print the updated array
print("Array with Rows Swapped:")
print(array)


Array with Rows Swapped:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


# 17.write a python code to reshape to the next diemension of numpy array?

In [16]:
import numpy as np

# Create a sample 1D array (replace this with your array)
original_array = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array to the next dimension (2D in this case)
reshaped_array = original_array.reshape(-1, 1)

# Print the original and reshaped arrays
print("Original Array:")
print(original_array)
print("\nReshaped Array:")
print(reshaped_array)


Original Array:
[1 2 3 4 5 6]

Reshaped Array:
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
